### ISSUE TITLE
cant start otmonitor

### ISSUE THREAD

**Issue by alexswart** [basschipper/docker-otmonitor#1]
Hello bas.

do you have change somting in the docker image?
i have reinstall my server and uploaded my old config an docker-compose file to the new server but otmonitor wont start.

my docker compose file is
`
version: '3'

services:
  otgw:
    image: basschipper/docker-otmonitor:latest
    container_name: otgw
    restart: always
    ports:
      - 8081:8081/tcp
    networks:
      - bridge
    volumes:
      - ./otmonitor.conf:/app/otmonitor.conf

networks:
  bridge:
`

and the config:
`web {
  enable true
  port 8081
  nopass true
  sslport 0
  graphlegend false
  theme default
  sslprotocols tls1,tls1.1,tls1.2
  certonly false
}
connection {
  device /dev/ttyUSB0
  type tcp
  enable true
  port 23
  host 192.168.1.10
}
server {
  enable true
  port 7686
  relay true
}
datalog {
  append false
  file /root/otdata.txt
  enable false
  itemlist {
    flame
    dhwmode
    chmode
    dhwenable
    diag
    fault
    outside
    temperature
    setpoint
    modulation
    boilertemp
    returntemp
    controlsp
    dhwsetpoint
    chwsetpoint
    timestamp
  }
  interval 30000
}
clock {
  year false
  date false
  auto false
}
mqtt {
  enable true
  devicetype central_heating
  deviceid otmonitor
  retransmit 10
  format raw
  port 1883
  qos 1
  keepalive 120
  username user
  password 
  messages true
  client otgw
  broker 192.168.1.102
}
sms {
  enable false
  ventilationfault false
  phonenumber {}
  route {}
  sender {}
  password c2VjcmV0
  provider VoipPlanet
  account {}
  pressure false
  solarfault false
  roomcold true
  watchdogtimer false
  boilerfault true
  commproblem false
}
email {
  password c2VjcmV0
  server {}
  pressure true
  roomcold true
  boilerfault true
  watchdogtimer true
  solarfault true
  commproblem true
  port 25
  enable false
  secure TLS
  recipient {}
  user {}
  sender {}
  ventilationfault true
}
logfile {
  pattern otlog-%Y%m%d.txt
  directory /root
  enable false
}
tspeak {
  key {}
  enable false
  interval 120
  field1 temperature
  field2 setpoint
  field3 boilertemp
  field4 returntemp
  field5 controlsp
  field6 modulation
  field7 {}
  field8 {}
}
alert {
  pressurelow 1.5
  roomcold 14
  pressurehigh 2.0
}
view {
  tab graph
  order increasing
  sort name
  bitflags false
}
`

**Comment by basschipper** [comment]
A while ago, I moved the otmonitor.conf to a separate directory. 
Change:
```yaml
volumes:
- ./otmonitor.conf:/app/otmonitor.conf
```
To:
```yaml
volumes:
- ./otmonitor.conf:/data/otmonitor.conf
```

**Comment by alexswart** [comment]
thank you that works.

my new docker-compose file is 

version: '3'

services:
  otgw:
    image: basschipper/docker-otmonitor:latest
    container_name: otgw
    restart: always
    ports:
      - 8080:8080/tcp
    networks:
      - bridge
    volumes:
      - ./otmonitor.conf:/data/otmonitor.conf

networks:
  bridge:
