### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Mio3000** [basschipper/docker-otmonitor#10]
Hi all,

could someone please share the config with me? I really dont know what config to use here, i started the container and it didnt create the *.conf file.

Thank you.

**Comment by basschipper** [comment]
This is about otmonitor's config, so actually you are not in the right place to ask your question. Pls have a look on the otmonitor's website: https://otgw.tclcode.com/
I no longer use this image myself, so I don't remember exactly, but I thought that at least with something like the below you should already be able to get into the web interface.

```
web {
  enable true
  port 8080
  nopass true
}
```

**Comment by Mio3000** [comment]
@basschipper this was i missing, it is working now... I was looking on that page for couple of days to find this info, but without luck, or im blind. also the original OT monitor, when i started it locally on my laptop, it did not create any conf file, it is just exe file.

Thank you for this info, now it is working correctly and im able to access the web interface
