### ISSUE TITLE
Question about running this container on Raspberry Pi4 B (8GB)

### ISSUE THREAD

**Issue by fallen2109** [basschipper/docker-otmonitor#3]
Hi Bas,

Frist of all - very Happy, Healty and Prosperous New 2021 Year. Wish you a lot of Love and Happiness to you and your loved ones!

In the past we have communicated over your otmonitor docker app and I was quite happy with it. 
I decided to minimize my setup and go from an old Lenove laptop to the latest Rapberry Pi4 (arm64). 

It seems however that your container only contains Intel compatible executables - correct? 
When running it on RPi 4 I am getting the following error:

WARNING: **The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested**
cde324824a038bc56f7934d9a3ad71c74cdc710fa56388a7114d314ebae4b383

Is there an easy way to crosscompile for arm64 ?

I did try also the latest loose binaries from the original site:

https://otgw.tclcode.com/download.html#sources

but they refuse to work on my Raspberry Pi (running Ubuntu 20.04 LTS).

Hoping that you have some time to answer my questions :). 
Stay safe and Kind Regards
Miroslav

**Comment by basschipper** [comment]
Not sure, this goes a bit beyond this docker image.
Maybe this page can help: https://otgw.tclcode.com/otmonsrc.html
Or file an issue with the developer of otmonitor: https://github.com/hvxl/otmonitor

**Comment by fallen2109** [comment]
Hi Bas,
Happy new 2021 year. Lots of Health, Happiness and Joy. 
Thank you for your reply. I did manage to run the latest binary (Dec 2020) from tje OTGW website. The RPI arm64 binary works perfectly under ubuntu 20.04 LTS in deamon mode (I do not have the graphical desktop installed).

Stay safe and keep up the good work.
Regards
Miroslav

**Comment by basschipper** [comment]
There's a not on the otgw website saying:
```
As the program is not updated frequently, it is possible that the libraries of a newer OS may not be the versions the program is expecting. In such cases you can usually install an older set of libraries next to the latest and greatest one.
```

So maybe this was the case with the older version?
